src/objects/Borrowing_Period__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Borrowing period configuration for library items</description>
    <fields>
        <fullName>AV_Equipment_Interval__c</fullName>
        <defaultValue>5</defaultValue>
        <description>The period of time a user can check out  AV Equipment</description>
        <label>AV Equipment Interval</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Book_Interval__c</fullName>
        <description>Length of time a person can check out a book</description>
        <label>Book Interval</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Borrowing Period</label>
</CustomObject>

src/objects/Library_Item__c.object
<CustomObject>
    <description>A reservable library item, such as a book or AV equipment</description>
    <fields>
        <fullName>Barcode__c</fullName>
        <description>Unique barcode value</description>
        <label>Barcode</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circulation_Status__c</fullName>
        <defaultValue>&quot;In Circulation&quot;</defaultValue>
        <label>Circulation Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Circulation</fullName>
                    <default>true</default>
                    <label>In Circulation</label>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Damaged</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Library Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Item</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Library_Item_Check_Out__c.object
<CustomObject>
    <description>History of Library Item Check Outs</description>
    <fields>
        <fullName>Borrower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user that checked out the library item</description>
        <label>Borrower</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Library_Item_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_Out_Status__c</fullName>
        <formula>IF (NOT(ISBLANK(Check_In_Time__c)), &quot;Checked In&quot;,
IF (Due_Back_Time__c &lt;= NOW(), &quot;Overdue&quot;,
&quot;Checked Out&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Check Out Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Library_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to checked-out library item</description>
        <label>Library Item</label>
        <referenceTo>Library_Item__c</referenceTo>
        <relationshipLabel>Library Item Check Out</relationshipLabel>
        <relationshipName>Library_Item_History</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Library Item Check Out</label>
    <nameField>
        <displayFormat>LIH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Item Check Out</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Library_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Library Configuration Information</description>
    <fields>
        <fullName>Barcode_Prefix__c</fullName>
        <defaultValue>&quot;1111&quot;</defaultValue>
        <description>Unique barcode prefix for library</description>
        <label>Barcode Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Library Settings</label>
</CustomObject>

src/classes/cfsLibraryItemCheckOut_Test.cls
@isTest
public class cfsLibraryItemCheckOut_Test {

    static testMethod void Execute() {
        
        Library_Item__c libraryItem;
        Library_Item_Check_Out__C libraryItemCheckOut;
        User borrower;
                
        //Load Test Data
        try {
        	insert new Library_Settings__c(Barcode_Prefix__c='3119');
        	insert new Borrowing_Period__c(AV_Equipment_Interval__c = 5, Book_Interval__c=14);
        	borrower = [SELECT Id FROM User WHERE Alias = 'starly'];

            libraryItem = new Library_Item__c();
            libraryItem.Name = 'Crime and Punishment';
            libraryItem.Barcode__c = '33119777777777';
            libraryItem.Circulation_Status__c = 'Retired';
            insert libraryItem;
            
            libraryItem = new Library_Item__c();
            libraryItem.Name = 'Pride and Prejudice';
            libraryItem.Barcode__c = '33119888888888';
            insert libraryItem;
            
            libraryItem = new Library_Item__c();
            libraryItem.Name = 'War and Peace';
            libraryItem.Barcode__c = '33119999999999';
            insert libraryItem;

        }        
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());        	
        }
        
        //Positive Tests

        //1. Check Out Available item
        try {
        	libraryItem =[SELECT ID from Library_Item__c WHERE Barcode__c = '33119888888888'];
        	cfsLibraryItemCheckOut.CheckOut(libraryItem.Id, borrower.Id);

			libraryItemCheckOut = [SELECT Id, Library_Item__c, Borrower__c, Check_Out_Status__c FROM Library_Item_Check_Out__c WHERE Library_Item__c = :libraryItem.Id AND Borrower__c = :borrower.Id];        	
            
            System.assertEquals(libraryItem.Id, libraryItemCheckOut.Library_Item__c);       
            System.assertEquals(borrower.Id, libraryItemCheckOut.Borrower__c);       
            System.assertEquals('Checked Out', libraryItemCheckOut.Check_Out_Status__c);     
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        
        //2. Check In valid item
        try {
        	libraryItem =[SELECT ID from Library_Item__c WHERE Barcode__c = '33119888888888'];
        	cfsLibraryItemCheckOut.CheckIn(libraryItem.Id);

			libraryItemCheckOut = [SELECT Id, Library_Item__c, Borrower__c, Check_Out_Status__c FROM Library_Item_Check_Out__c WHERE Library_Item__c = :libraryItem.Id AND Borrower__c = :borrower.Id];        	
            
            System.assertEquals(libraryItem.Id, libraryItemCheckOut.Library_Item__c);            
            System.assertEquals(borrower.Id, libraryItemCheckOut.Borrower__c);            
            System.assertEquals('Checked In', libraryItemCheckOut.Check_Out_Status__c);     
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        
        //3. Valid List
        try {
	        List<String> statuses = new List<String>{cfsLibraryItemCheckOut.CHECKED_OUT, cfsLibraryItemCheckOut.OVERDUE, cfsLibraryItemCheckOut.CHECKED_IN};
        	List<Library_Item_Check_Out__c> libraryItemCheckOutList = cfsLibraryItemCheckOut.GetList(borrower.Id, statuses);
            
            System.assertEquals(1, libraryItemCheckOutList.size());     
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        

        //Negative Tests

        //1. Check Out duplicate item
        try {            
        	libraryItem =[SELECT ID from Library_Item__c WHERE Barcode__c = '33119888888888'];
        	cfsLibraryItemCheckOut.CheckOut(libraryItem.Id, borrower.Id);
        	libraryItem =[SELECT ID from Library_Item__c WHERE Barcode__c = '33119888888888'];
        	cfsLibraryItemCheckOut.CheckOut(libraryItem.Id, borrower.Id);
           
            System.Assert(false, 'Duplicate check out not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }        

        //2. Check Out Unavailable item
        try {            
        	libraryItem =[SELECT ID from Library_Item__c WHERE Barcode__c = '33119777777777'];
        	cfsLibraryItemCheckOut.CheckOut(libraryItem.Id, borrower.Id);
            
            System.Assert(false, 'Unavailable check out not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }        

        //3. Check Out invalid Library Item
        try {            
        	cfsLibraryItemCheckOut.CheckOut(NULL, borrower.Id);
            
            System.Assert(false, 'Invalid library item not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }        

        //4. Check Out invalid borrowerId
        try {            
        	libraryItem =[SELECT ID from Library_Item__c WHERE Barcode__c = '33119999999999'];
        	cfsLibraryItemCheckOut.CheckOut(libraryItem.Id, NULL);
            
            System.Assert(false, 'Invalid borrowerid get not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }        

        //5. Check In invalid Library Item
        try {            
        	cfsLibraryItemCheckOut.CheckIn(NULL);
            
            System.Assert(false, 'Invalid library item not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }
        
        //6. Invalid List input
        try {            
        	List<Library_Item_Check_Out__c> libraryItemCheckOutList = cfsLibraryItemCheckOut.GetList(borrower.Id, NULL);
            
            System.Assert(false, 'Invalid GetList statuses not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }
   }
}