src/objects/Borrowing_Period__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Borrowing period configuration for library items</description>
    <label>Borrowing Period</label>
</CustomObject>

src/objects/Library_Item_Limit__c.object
<CustomObject>
    <description>Borrowing limit for Library Item per category</description>
    <fields>
        <fullName>Borrowing_Limit__c</fullName>
        <formula>CASE (TEXT( Borrowing_Period__c ),
&apos;Days&apos;,  Borrowing_Period_Interval__c, 
&apos;Hours&apos;, Borrowing_Period_Interval__c / 24,
14
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Borrowing Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Borrowing_Period_Interval__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Borrowing Period Interval</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Borrowing_Period__c</fullName>
        <label>Borrowing Period</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hours</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                    <default>true</default>
                    <label>Days</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Library Item category that this borrowing limit applies.</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Library_Item_Category</valueSetName>
        </valueSet>
    </fields>
    <label>Library Item Limit</label>
    <nameField>
        <displayFormat>LIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Item Limits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Library_Item_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Book</fullName>
        <default>true</default>
        <label>Book</label>
    </customValue>
    <customValue>
        <fullName>Magazine</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <customValue>
        <fullName>DVD</fullName>
    </customValue>
    <customValue>
        <fullName>Projectors</fullName>
    </customValue>
    <customValue>
        <fullName>Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Monitors</fullName>
    </customValue>
    <customValue>
        <fullName>Televisions</fullName>
    </customValue>
    <customValue>
        <fullName>Cables</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Library Item Category</masterLabel>
</GlobalValueSet>

src/classes/cfs_LibraryItemLimitsSelector.cls
public with sharing class cfs_LibraryItemLimitsSelector extends fflib_SObjectSelector {
	
    public List<Schema.SObjectField> getSObjectFieldList() {
    	return new List<Schema.SObjectField> {
    		Library_Item_Limit__c.Id,
    		Library_Item_Limit__c.Name,
    		Library_Item_Limit__c.Category__c,
			Library_Item_Limit__c.Borrowing_Period__c,
			Library_Item_Limit__c.Borrowing_Period_Interval__c,
			Library_Item_Limit__c.Borrowing_Limit__c
    		};
    }
       
    public Schema.SObjectType getSObjectType() {
    	return Library_Item_Limit__c.SObjectType;	
    }

    public List<Library_Item_Limit__c> selectById(Set<Id> libraryItemLimitIds) {
    	return (List<Library_Item_Limit__c>) selectSObjectsById(libraryItemLimitIds);
    }


	public List<Library_Item_Limit__c> selectDuplicatesByCategory(Map<Id,String> categoryMap) {
		fflib_QueryFactory queryFactory = newQueryFactory();
		List<String> categories = categoryMap.values();
		Set<Id> excludedIds = categoryMap.keySet();
		queryFactory.setCondition('Category__c IN :categories AND Id NOT IN : excludedIds');
		return (List<Library_Item_Limit__c>) Database.query(queryFactory.toSOQL());
	}

	public Map<String,String> getMapOfDuplicateNamesByCategory(List<Library_Item_Limit__c> libraryItemLimits) {
		Map<String, String> returnMap = new Map<String,String>();
		Map<Id,String> categoryMap = cfs_LibraryItemLimitsHelper.getCategoryMap(libraryItemLimits);
		List<Library_Item_Limit__c> duplicateLibraryItemLimits = this.selectDuplicatesByCategory(categoryMap);
		for (Library_Item_Limit__c libraryItemLimit : duplicateLibraryItemLimits) {
			returnMap.put(libraryItemLimit.Category__c, libraryItemLimit.Name);
		}
		return returnMap;
	}
}