src/objects/Borrowing_Period__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Borrowing period configuration for library items</description>
    <fields>
        <fullName>AV_Equipment_Interval__c</fullName>
        <defaultValue>5</defaultValue>
        <description>The period of time a user can check out  AV Equipment</description>
        <label>AV Equipment Interval</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Book_Interval__c</fullName>
        <description>Length of time a person can check out a book</description>
        <label>Book Interval</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Borrowing Period</label>
</CustomObject>

src/objects/Library_Item__c.object
<CustomObject>
    <description>A reservable library item, such as a book or AV equipment</description>
    <fields>
        <fullName>Availability_Status__c</fullName>
        <formula>IF ( TEXT(Circulation_Status__c) != &apos;In Circulation&apos;, TEXT(Circulation_Status__c),
IF ( ISBLANK(Current_Check_Out__c), &apos;Available&apos;,
CASE ( Current_Check_Out__r.Check_Out_Status__c,
       &apos;Checked In&apos;, &apos;Available&apos;,
       Current_Check_Out__r.Check_Out_Status__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Availability Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Barcode__c</fullName>
        <description>Unique barcode value</description>
        <label>Barcode</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circulation_Status__c</fullName>
        <defaultValue>&quot;In Circulation&quot;</defaultValue>
        <label>Circulation Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Circulation</fullName>
                    <default>true</default>
                    <label>In Circulation</label>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Damaged</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Check_Out__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the current check-out  of this library resource</description>
        <label>Current Check Out</label>
        <referenceTo>Library_Item_Check_Out__c</referenceTo>
        <relationshipLabel>Current Library Item</relationshipLabel>
        <relationshipName>Current_Library_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Library Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Item</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Library_Item_Check_Out__c.object
<CustomObject>
    <description>History of Library Item Check Outs</description>
    <fields>
        <fullName>Borrower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user that checked out the library item</description>
        <label>Borrower</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Library_Item_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_In_Time__c</fullName>
        <description>The date and time the library item was checked in</description>
        <label>Check In Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Check_Out_Status__c</fullName>
        <formula>IF (NOT(ISBLANK(Check_In_Time__c)), &quot;Checked In&quot;,
IF (Due_Back_Time__c &lt;= NOW(), &quot;Overdue&quot;,
&quot;Checked Out&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Check Out Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Library_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to checked-out library item</description>
        <label>Library Item</label>
        <referenceTo>Library_Item__c</referenceTo>
        <relationshipLabel>Library Item Check Out</relationshipLabel>
        <relationshipName>Library_Item_History</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Library Item Check Out</label>
    <nameField>
        <displayFormat>LIH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Item Check Out</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Library_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Library Configuration Information</description>
    <fields>
        <fullName>Barcode_Prefix__c</fullName>
        <defaultValue>&quot;1111&quot;</defaultValue>
        <description>Unique barcode prefix for library</description>
        <label>Barcode Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Library Settings</label>
</CustomObject>

src/classes/cfsLibraryItemCheckOut_Trigger_Test.cls
@isTest
public class cfsLibraryItemCheckOut_Trigger_Test {

    static testMethod void Execute() {
        
        User borrower;
        Library_Item__c libraryItem;
        Library_Item_Check_Out__c libraryItemCheckOut;
        Boolean valid;
        
        //Load test data
        try {
        	insert new Library_Settings__c(Barcode_Prefix__c='3119');
        	insert new Borrowing_Period__c(AV_Equipment_Interval__c = 5, Book_Interval__c=14);	
        	borrower = [SELECT Id FROM User WHERE Alias = 'starly'];
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        try {
            libraryItem = new Library_Item__c();
            libraryItem.Name = 'Pride and Prejudice';
            libraryItem.Barcode__c = '33119888888888';
            insert libraryItem;            
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }

        //Positive Tests
        
        //1. Insert one valid record
        try {
            libraryItemCheckOut = new Library_Item_Check_Out__c();
            libraryItemCheckOut.Library_Item__c = libraryItem.Id;
            libraryItemCheckOut.Borrower__c = borrower.Id;
            insert libraryItemCheckOut;
            
            libraryItemCheckOut = [SELECT Id, Check_Out_Status__c FROM Library_Item_Check_Out__c WHERE Id = :libraryItemCheckOut.Id];            
            libraryItem = [SELECT Id, Availability_Status__c, Current_Check_Out__c FROM Library_Item__c WHERE Id = :LibraryItem.Id];
            
            System.assertEquals('Checked Out', libraryItemCheckOut.Check_Out_Status__c);
            System.assertEquals(libraryItemCheckOut.Id, libraryItem.Current_Check_Out__c);
            System.assertEquals('Checked Out', libraryItem.Availability_Status__c);	
			}        
			catch (Exception ex) {
            	System.Assert(false, ex.getMessage());
        }
        
        //2. Change one record
        try {            
            libraryItemCheckOut = [SELECT Id FROM Library_Item_Check_Out__c WHERE Id = :libraryItemCheckOut.Id];
            libraryItemCheckOut.Check_In_Time__c = Datetime.now();
            update libraryItemCheckOut;
            
            libraryItemCheckOut = [SELECT Id, Check_Out_Status__c FROM Library_Item_Check_Out__c WHERE Id = :libraryItemCheckOut.Id];            
            libraryItem = [SELECT Id, Availability_Status__c, Current_Check_Out__c FROM Library_Item__c WHERE Id = :LibraryItem.Id];
            
            System.assertEquals('Checked In', libraryItemCheckOut.Check_Out_Status__c);
            System.assertEquals(NULL, libraryItem.Current_Check_Out__c);
            System.assertEquals('Available', libraryItem.Availability_Status__c);	
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        
        //Negative Tests
        
        //1. Insert duplicate
        try {
            libraryItemCheckOut = new Library_Item_Check_Out__c();
            libraryItemCheckOut.Library_Item__c = libraryItem.Id;
            libraryItemCheckOut.Borrower__c = borrower.Id;
            insert libraryItemCheckOut;
            insert libraryItemCheckOut;

            System.Assert(false, 'Duplicate insert not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }
        
        //1. Insert not available
        try {
            libraryItemCheckOut = [SELECT Id FROM Library_Item_Check_Out__c WHERE Id = :libraryItemCheckOut.Id];
            libraryItemCheckOut.Check_In_Time__c = Datetime.now();
            update libraryItemCheckOut;

            libraryItem = [SELECT Id FROM Library_Item__c WHERE Id = :LibraryItem.Id];
            libraryItem.Circulation_Status__c = 'Damaged';            
            update libraryItem;
        	
            libraryItemCheckOut = new Library_Item_Check_Out__c();
            libraryItemCheckOut.Library_Item__c = libraryItem.Id;
            libraryItemCheckOut.Borrower__c = borrower.Id;
            insert libraryItemCheckOut;
            
            System.Assert(false, 'Unavailable insert not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }
    }
}