src/objects/Borrowing_Period__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Borrowing period configuration for library items</description>
    <fields>
        <fullName>AV_Equipment_Interval__c</fullName>
        <defaultValue>5</defaultValue>
        <description>The period of time a user can check out  AV Equipment</description>
        <label>AV Equipment Interval</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Book_Interval__c</fullName>
        <description>Length of time a person can check out a book</description>
        <label>Book Interval</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Borrowing Period</label>
</CustomObject>

src/objects/Library_Item__c.object
<CustomObject>
    <description>A reservable library item, such as a book or AV equipment</description>
    <fields>
        <fullName>Availability_Status__c</fullName>
        <formula>IF ( TEXT(Circulation_Status__c) != &apos;In Circulation&apos;, TEXT(Circulation_Status__c),
IF ( ISBLANK(Current_Check_Out__c), &apos;Available&apos;,
CASE ( Current_Check_Out__r.Check_Out_Status__c,
       &apos;Checked In&apos;, &apos;Available&apos;,
       Current_Check_Out__r.Check_Out_Status__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Availability Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Barcode__c</fullName>
        <description>Unique barcode value</description>
        <label>Barcode</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Circulation_Status__c</fullName>
        <defaultValue>&quot;In Circulation&quot;</defaultValue>
        <label>Circulation Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Circulation</fullName>
                    <default>true</default>
                    <label>In Circulation</label>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Damaged</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Library Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Item</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Library_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Library Configuration Information</description>
    <fields>
        <fullName>Barcode_Prefix__c</fullName>
        <defaultValue>&quot;1111&quot;</defaultValue>
        <description>Unique barcode prefix for library</description>
        <label>Barcode Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Library Settings</label>
</CustomObject>

src/classes/cfsLibraryItem_Trigger_Test.cls
@isTest
public class cfsLibraryItem_Trigger_Test {

    static testMethod void Execute() {
        
        Library_Item__c libraryItem;
                
        //Load Test Data
        try {
        	insert new Library_Settings__c(Barcode_Prefix__c='3119');
        	insert new Borrowing_Period__c(AV_Equipment_Interval__c = 5, Book_Interval__c=14);	
        }        
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());        	
        }
        
        //Positive Tests

        //1. Insert one valid record
        try {
            libraryItem = new Library_Item__c();
            libraryItem.Name = 'Crime and Punishment';
            libraryItem.Barcode__c = '33119999999999';
            insert libraryItem;
            
            libraryItem = [SELECT Id, Availability_Status__c FROM Library_Item__c WHERE Barcode__c = '33119999999999'];
            
            System.assertEquals('Available', libraryItem.Availability_Status__c);            
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        
        //2. Change one record
        try {            
            libraryItem = [SELECT Id FROM Library_Item__c WHERE Barcode__c = '33119999999999'];
            libraryItem.Circulation_Status__c = 'Damaged';            
            update libraryItem;
            
            libraryItem = [SELECT Id, Availability_Status__c FROM Library_Item__c WHERE Barcode__c = '33119999999999'];
            
            System.assertEquals('Damaged', libraryItem.Availability_Status__c);            
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        
        //Negative Tests
        
        //1. Insert duplicate
        try {
            libraryItem = new Library_Item__c();
            libraryItem.Name = 'Tale of Two Cities';
            libraryItem.Barcode__c = '33119999999999';
            insert libraryItem;
                        
            System.Assert(false, 'Duplicate insert not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }
        
        //2. Enter invalid barcode
        try {            
            libraryItem = [SELECT Id FROM Library_Item__c WHERE Barcode__c = '33119999999999'];
            libraryItem.Barcode__c = '2311801';
            update libraryItem;
            
            System.Assert(false, 'Invalid barcode not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }        
        //3. Enter missing name
        try {
            libraryItem = new Library_Item__c();
            libraryItem.Name = '';
            libraryItem.Barcode__c = '33119888888888';
            insert libraryItem;
                        
            System.Assert(false, 'No name insert not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }
    }
}