src/objects/Borrowing_Period__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Borrowing period configuration for library items</description>
    <fields>
        <fullName>AV_Equipment_Interval__c</fullName>
        <defaultValue>5</defaultValue>
        <description>The period of time a user can check out  AV Equipment</description>
        <label>AV Equipment Interval</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Book_Interval__c</fullName>
        <description>Length of time a person can check out a book</description>
        <label>Book Interval</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Borrowing Period</label>
</CustomObject>

src/objects/Library_Item__c.object
<CustomObject>
    <description>A reservable library item, such as a book or AV equipment</description>
    <fields>
        <fullName>Barcode__c</fullName>
        <description>Unique barcode value</description>
        <label>Barcode</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <label>Library Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Item</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Library_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Library Configuration Information</description>
    <fields>
        <fullName>Barcode_Prefix__c</fullName>
        <defaultValue>&quot;1111&quot;</defaultValue>
        <description>Unique barcode prefix for library</description>
        <label>Barcode Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Library Settings</label>
</CustomObject>

src/classes/cfsLibraryItem_Test.cls
@isTest
public class cfsLibraryItem_Test {

    static testMethod void Execute() {
        
        Library_Item__c libraryItem;
                
        //Load Test Data
        try {
        	insert new Library_Settings__c(Barcode_Prefix__c='3119');
        	insert new Borrowing_Period__c(AV_Equipment_Interval__c = 5, Book_Interval__c=14);

            libraryItem = new Library_Item__c();
            libraryItem.Name = 'Crime and Punishment';
            libraryItem.Barcode__c = '33119777777777';
            insert libraryItem;
            
            libraryItem = new Library_Item__c();
            libraryItem.Name = 'Pride and Prejudice';
            libraryItem.Barcode__c = '33119888888888';
            insert libraryItem;
            
            libraryItem = new Library_Item__c();
            libraryItem.Name = 'War and Peace';
            libraryItem.Barcode__c = '33119999999999';
            insert libraryItem;

        }        
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());        	
        }
        
        //Positive Tests

        //1. Get a valid record
        try {
        	libraryItem = cfsLibraryItem.Get('33119888888888');
            
            System.assertEquals('Pride and Prejudice', libraryItem.Name);            
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        
        //2. Get Availability Status
        try {
        	Boolean isAvailable = cfsLibraryItem.IsAvailable('Available');
            
            System.assertEquals(true, isAvailable);            
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        
        //Negative Tests
        //1. Get a invalid record
        try {            
        	libraryItem = cfsLibraryItem.Get('33119111111111');
            
            System.Assert(false, 'Invalid record get not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }        
   }
}