src/objects/Borrowing_Period__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Borrowing period configuration for library items</description>
    <label>Borrowing Period</label>
</CustomObject>

src/objects/Library_Item_Limit__c.object
<CustomObject>
    <description>Borrowing limit for Library Item per category</description>
    <fields>
        <fullName>Borrowing_Limit__c</fullName>
        <formula>CASE (TEXT( Borrowing_Period__c ),
&apos;Days&apos;,  Borrowing_Period_Interval__c, 
&apos;Hours&apos;, Borrowing_Period_Interval__c / 24,
14
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Borrowing Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Borrowing_Period_Interval__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Borrowing Period Interval</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Borrowing_Period__c</fullName>
        <label>Borrowing Period</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hours</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                    <default>true</default>
                    <label>Days</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Library Item category that this borrowing limit applies.</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Library_Item_Category</valueSetName>
        </valueSet>
    </fields>
    <label>Library Item Limit</label>
    <nameField>
        <displayFormat>LIL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Item Limits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Library_Item_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Book</fullName>
        <default>true</default>
        <label>Book</label>
    </customValue>
    <customValue>
        <fullName>Magazine</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <customValue>
        <fullName>DVD</fullName>
    </customValue>
    <customValue>
        <fullName>Projectors</fullName>
    </customValue>
    <customValue>
        <fullName>Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Monitors</fullName>
    </customValue>
    <customValue>
        <fullName>Televisions</fullName>
    </customValue>
    <customValue>
        <fullName>Cables</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Library Item Category</masterLabel>
</GlobalValueSet>

src/classes/cfsLibraryItemLimit_Trigger_Test.cls
@isTest
public class cfsLibraryItemLimit_Trigger_Test {
    
    static testMethod void Execute() {
        
        Library_Item_Limit__c libraryItemLimit;
        
        //Positive Tests
        
        //1. Insert one valid record
        try {
            libraryItemLimit = new Library_Item_Limit__c ();
            libraryItemLimit.Category__c = 'Book';
            libraryItemLimit.Borrowing_Period__c = 'Days';
            libraryItemLimit.Borrowing_Period_Interval__c = 14;        
            insert libraryItemLimit;
            
            libraryItemLimit = [SELECT Id, Borrowing_Limit__c FROM Library_Item_Limit__c WHERE Category__c = 'Book'];
            
            System.assertEquals(14.0, libraryItemLimit.Borrowing_Limit__c);            
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        
        //2. Change one record from Days to Hours
        try {            
            libraryItemLimit = [SELECT Id FROM Library_Item_Limit__c WHERE Category__c = 'Book'];
            
            libraryItemLimit.Borrowing_Period__c = 'Hours';
            libraryItemLimit.Borrowing_Period_Interval__c = 48;        
            update libraryItemLimit;
            
            libraryItemLimit = [SELECT Id, Borrowing_Limit__c FROM Library_Item_Limit__c WHERE Category__c = 'Book'];
            
            System.assertEquals(2.0, libraryItemLimit.Borrowing_Limit__c);            
        }
        catch (Exception ex) {
            System.Assert(false, ex.getMessage());
        }
        
        //Negative Tests
        
        //1. Insert duplicate
        try {
            libraryItemLimit = new Library_Item_Limit__c ();
            libraryItemLimit.Category__c = 'Book';
            libraryItemLimit.Borrowing_Period__c = 'Days';
            libraryItemLimit.Borrowing_Period_Interval__c = 14;        
            insert libraryItemLimit;
            
            System.Assert(false, 'Duplicate insert not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }
        
        //2. Enter negative limit
        try {            
            libraryItemLimit = [SELECT Id FROM Library_Item_Limit__c WHERE Category__c = 'Book'];
            
            libraryItemLimit.Borrowing_Period__c = 'Hours';
            libraryItemLimit.Borrowing_Period_Interval__c = -1;        
            update libraryItemLimit;
            
            System.Assert(false, 'Negative interval not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }
        
        //3. Enter zero limit
        try {            
            libraryItemLimit = [SELECT Id FROM Library_Item_Limit__c WHERE Category__c = 'Book'];
            
            libraryItemLimit.Borrowing_Period__c = 'Hours';
            libraryItemLimit.Borrowing_Period_Interval__c = 0;        
            update libraryItemLimit;
            
            System.Assert(false, 'Zero interval not rejected');            
        }
        catch (Exception ex) {
            System.Assert(true, ex.getMessage());
        }
        
    }
}