src/objects/Library_Item__c.object
<CustomObject>
    <description>A reservable library item, such as a book or AV equipment</description>
    <fields>
        <fullName>Availability_Status__c</fullName>
        <formula>IF ( TEXT(Circulation_Status__c) != &apos;In Circulation&apos;, TEXT(Circulation_Status__c),
IF ( ISBLANK(Current_Check_Out__c), &apos;Available&apos;,
CASE ( Current_Check_Out__r.Check_Out_Status__c,
       &apos;Checked In&apos;, &apos;Available&apos;,
       Current_Check_Out__r.Check_Out_Status__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Availability Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Barcode__c</fullName>
        <description>Unique barcode value</description>
        <label>Barcode</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <label>Library Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Item</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Library_Item_Check_Out__c.object
<CustomObject>
    <description>History of Library Item Check Outs</description>
    <fields>
        <fullName>Library_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to checked-out library item</description>
        <label>Library Item</label>
        <referenceTo>Library_Item__c</referenceTo>
        <relationshipLabel>Library Item Check Out</relationshipLabel>
        <relationshipName>Library_Item_History</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Library Item Check Out</label>
    <nameField>
        <displayFormat>LIH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Item Check Out</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/cfsLibraryItemController.cls
public class cfsLibraryItemController {
    
    //Checks out a Library Item
    //Library Item is found using the given barcode
    //		Validation:
    //			Borrower and Library Item (via barcode) must be specified
    //    		Library Item must be available - in circulation and not already be checked out
    //
    @AuraEnabled
    public static void cfsCheckOut (String barcode, String borrowerRecordId) {
        if (String.isEmpty(borrowerRecordId)) {
            throw new AuraHandledException('Select a borrower before checking out a Library Item');
        }
        Library_Item__c libraryItem;
        try {
            libraryItem = cfsLibraryItem.Get(barcode);
            
            if (libraryItem != null && cfsLibraryItem.IsAvailable(libraryItem.Availability_Status__c)) {
                cfsLibraryItemCheckOut.CheckOut(libraryItem.Id, borrowerRecordId);
            }
        }
        catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        if (!cfsLibraryItem.IsAvailable(libraryItem.Availability_Status__c)) {
            throw new AuraHandledException('"' + libraryItem.Name + '" (' + libraryItem.Barcode__c + ') is not available for check out: ' + libraryItem.Availability_Status__c);
        }
    }
    
    //Checks in a Library Item
    //Library Item is found using the given barcode
    //		Validation:
    //			Library Item must be specified and exist
    //
    @AuraEnabled
    public static void cfsCheckIn (String barcode) {
    	Library_Item__c libraryItem;
        try {
            libraryItem = cfsLibraryItem.Get(barcode);
            
            if (libraryItem != null && libraryItem.Id != null) {
                cfsLibraryItemCheckOut.CheckIn(libraryItem.Id);                
            }
        }
        catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    //Returns a list of Checked Out Library Item Check Outs, including Overdue items, for a given Borrower
    //		Validation:
    //			Library Item must be specified and exist
    //    
    @AuraEnabled
    public static List<Library_Item_Check_Out__c> cfsListCurrentLibraryItemCheckOuts (String borrowerRecordId) {
        List<Library_Item_Check_Out__c> libraryItemCheckOuts = new List<Library_Item_Check_Out__c>();
        if (String.isEmpty(borrowerRecordId)) {
            return libraryItemCheckOuts;
        }
        try {
            
            List<String> checkedOutStatuses = new List<String>{cfsLibraryItemCheckOut.CHECKED_OUT, cfsLibraryItemCheckOut.OVERDUE};
                libraryItemCheckOuts = cfsLibraryItemCheckOut.GetList(borrowerRecordId, checkedOutStatuses);
            return libraryItemCheckOuts;
        }
        catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}