src/objects/Library_Item__c.object
<CustomObject>
    <description>A reservable library item, such as a book or AV equipment</description>
    <label>Library Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Item</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Library_Item_Check_Out__c.object
<CustomObject>
    <description>History of Library Item Check Outs</description>
    <fields>
        <fullName>Borrower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user that checked out the library item</description>
        <label>Borrower</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Library_Item_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_In_Time__c</fullName>
        <description>The date and time the library item was checked in</description>
        <label>Check In Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Check_Out_Status__c</fullName>
        <formula>IF (NOT(ISBLANK(Check_In_Time__c)), &quot;Checked In&quot;,
IF (Due_Back_Time__c &lt;= NOW(), &quot;Overdue&quot;,
&quot;Checked Out&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Check Out Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Back_Time__c</fullName>
        <description>Date and time the library item is scheduled to be returned</description>
        <label>Due Back Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Library_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to checked-out library item</description>
        <label>Library Item</label>
        <referenceTo>Library_Item__c</referenceTo>
        <relationshipLabel>Library Item Check Out</relationshipLabel>
        <relationshipName>Library_Item_History</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>Library_Item__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Library Item Check Out</label>
    <nameField>
        <displayFormat>LIH-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Item Check Out</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/cfsLibraryItemCheckOut.cls
public with sharing class cfsLibraryItemCheckOut {
    
    public static final String CHECKED_IN = 'Checked In';
    public static final String CHECKED_OUT = 'Checked Out';
    public static final String OVERDUE = 'Overdue';
    
    //Checks out a Library Item by creating a Library Item Check Out record
    //Borrower and Library Item must be specified and exist
    //		Defaults:
    //			Check Out Status is defaulted to the 'Checked Out' by field definition
    //			Checked Out Time is defaulted to current time by field definition
    //
    public static void CheckOut (ID libraryItemRecordId, ID borrowerRecordId) {
        Library_Item_Check_Out__c libraryItemCheckOut = new Library_Item_Check_Out__c();
        try {            
            libraryItemCheckOut.Library_Item__c = libraryItemRecordId;
            libraryItemCheckOut.Borrower__c = borrowerRecordId;
            
            insert libraryItemCheckOut;
        }
        catch (Exception ex) {
            throw new cfsLibraryException('Library Item Check Out creation failed', ex);
        }
    }
    
    //Checks in a Library Item Check Out by setting the 'Checked In Time' to the current time 
    //for any 'Checked Out' Library Item Check Out records for the given Library Item
    //Note: Before Insert and Before Update triggers validate that only one 'Checked Out' Library Item Check Out record exists for a Library Item
    //Borrower is not required. Library Item must be specified and exist
    //
    public static void CheckIn (ID libraryItemRecordId) {
        List<Library_Item_Check_Out__c> libraryItemCheckOuts = new List<Library_Item_Check_Out__c>();
        try {
	        if (String.isEmpty(libraryItemRecordId)) {
    	        throw new cfsLibraryException('Invalid Library Item Id');
        	}
            libraryItemCheckOuts = [SELECT Id FROM Library_Item_Check_Out__c 
                                    WHERE (Library_Item__c = :libraryItemRecordId 
                                           AND Check_Out_Status__c != :CHECKED_IN)];
            if ((libraryItemCheckOuts != null) && (!libraryItemCheckOuts.isEmpty())) {
                for (Library_Item_Check_Out__c libraryItemCheckOut : libraryItemCheckOuts) {
                    libraryItemCheckOut.Check_In_Time__c = Datetime.now();
                }
                update libraryItemCheckOuts;
            }
        }
        catch (Exception ex) {
            throw new cfsLibraryException('Library Item Check In failed', ex);            
        }
    }
    
    //Returns a list of Library Item Check Outs for the given Borrower that have a Checked Out Status in the given status list
    //Borrower must exist. Status list must not be NULL
    //    
    public static List<Library_Item_Check_Out__c> GetList (String borrowerRecordId, List<String> checkOutStatusList) {
        List<Library_Item_Check_Out__c> libraryItemCheckOuts = new List<Library_Item_Check_Out__c>();
        try {
            libraryItemCheckOuts = [SELECT Id, Name, Title__c, Borrower__c, Library_Item__c, Check_Out_Status__c, Due_Back_Time__c 
                                    FROM Library_Item_Check_Out__c 
                                    WHERE (borrower__c = :borrowerRecordId
                                           AND Check_Out_Status__c IN :checkOutStatusList)];            
            return libraryItemCheckOuts;
        }
        catch (Exception ex) {
            throw new cfsLibraryException('Library Item Check List failed', ex);                        
        }
    }
}