src/objects/Library_Item__c.object
<CustomObject>
    <description>A reservable library item, such as a book or AV equipment</description>
    <fields>
        <fullName>Availability_Status__c</fullName>
        <formula>IF ( TEXT(Circulation_Status__c) != &apos;In Circulation&apos;, TEXT(Circulation_Status__c),
IF ( ISBLANK(Current_Check_Out__c), &apos;Available&apos;,
CASE ( Current_Check_Out__r.Check_Out_Status__c,
       &apos;Checked In&apos;, &apos;Available&apos;,
       Current_Check_Out__r.Check_Out_Status__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Availability Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Barcode__c</fullName>
        <description>Unique barcode value</description>
        <label>Barcode</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <label>Library Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Item</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/cfsLibraryItem.cls
public with sharing class cfsLibraryItem {

    private static final String AVAILABLE = 'Available';

    public static Boolean IsAvailable(String availabilityStatus) {
        return (availabilityStatus == AVAILABLE);
    }

    //Returns the Library Item for the given barcode
    //Note: Before Insert and Before Update triggers validate that a Library Item is assigned a unique barcode
    //Barcode specified must be assigned on an existing Library Item
    //
    public static Library_Item__c Get (String barcode) {
        Library_Item__c libraryItem;
        try {
            libraryItem = [SELECT Id, Name, Barcode__c, Availability_Status__c FROM Library_Item__c WHERE barcode__c = :barcode ];  
            return libraryItem;
        }
        catch (Exception ex) {
	        throw new cfsLibraryException ('Library Item could not be found. Barcode: ' + barcode, ex);
        }
    }    
}